openapi: 3.0.0
info:
  description: >-
    This API returns valid test certfiicates for HGV/PSVs. This API is for DVLA(EVL) data consumption
  version: 1.0.0
  title: 'DVLA(EVL) Micorservice'
  termsOfService: ''
  contact:
    email: 'ujaffer@deloitte.co.uk'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /:
    get:
      tags:
        - 'test-certificates'
      summary: 'Returns an array of valid test certificates.'
      description: 'Returns valid test certificates of HGV/PSVs for the current day.'
      responses:
        200:
          description: 'Certificates returned based on search filter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testCertificates'
components:
  schemas:
     testCertificates:
      type: array
      items:
        $ref: '#/components/schemas/testCertificate'
     testCertificate:
      type: object
      properties:
        currentRegMark:
          type: string
          description: 'Current Registration Mark'
        certificateSerialNumber:
          type: string
          description: 'Certificate Serial Number'
          maxLength: 8
        certificateExpiryDate:
          type: string
          description: 'Expiry date of the certificate.'
security:
  - ApiKeyAuth: []
  - OAuth2:
      - read
servers:
  - url: 'https://url/api/v1'